### ISSUE TITLE
proposal for a general fork

### ISSUE THREAD

**Issue by joey04** [joey04/xulBlock-Advanced#2]
Earlier today I posted a "Proposal for a general fork of uBlock Origin for XUL browsers" on the Pale Moon forum:
https://forum.palemoon.org/viewtopic.php?f=46&t=18188

I'm leaving that as-is. All the info is still relevant, but for doing the actual project coordination and hand-off work, it'll all be here at this issue. After all, the project will be on GitHub anyways.

Please respond here if you're seriously interested or already willing to take ownership of this proposed uBO-alike general fork.

**Comment by joey04** [comment]
It occurred to me after posting my Proposal that I had the approach backwards. The end-result is the same, but it's a lot easier to _start_ with stock uBO 1.14.16 _then_ patch it from my xBA 1.0 with what is appropriate for a uBO-alike general fork.

And the good news -- it's done!

[uBO 1.14.16+bp1.zip](https://github.com/joey04/xulBlock-Advanced/files/1676444/uBO.1.14.16.bp1.zip)

(GitHub won't accept a .xpi upload so I renamed to .zip)

<hr>

The backports are:
* https://github.com/gorhill/uBlock/commit/178b82eb6aa5e7cf7caf6bb891c9733718c7e330
* https://github.com/gorhill/uBlock/commit/36956cbc7a971ae397615f38bbbaff92d5a5a7ca
* https://github.com/gorhill/uBlock/commit/636dcf7ee4a15596b36e6f6a42bd9330c08a7374
* `yamd5.js` removed - unused and gorhill removed already in a more recent version

And as a bonus, I removed https://github.com/gorhill/uBlock/commit/126110c9a0a0630cd556f5cb215422296a961029 just because :)

<hr>

So, how to proceed from here?

For starters, I only tested it for a couple of minutes on Pale Moon with the default uBO settings. I forced a full list update and went to a few sites. Everything appears to be fine, but it definitely should be tested more rigorously. I'd recommend simultaneous comparison tests with stock 1.14.16 on another browser or profile to be certain the backports aren't causing regressions.

Note I said "I'd recommend" because this is a good point for me to step back and let someone else take over.

Also note that:
* I'm still willing to assist with this uBO-alike fork effort. It could be code reviews, decision-making advice, or similar.
* Since this new uBO-alike shares the same fork point as xBA, we're peer projects that can easily share patches, ideas, etc.

So hopefully you don't think I'm just looking to handoff a backported .xpi then wish you well. There probably will be specific ways we'd mutually benefit by working together.

**Comment by joey04** [comment]
I just realized that despite writing many words already, I had not yet clearly stated the reasons why I am not willing to take ownership of my proposed uBO-alike fork. The reasons are:
* I don't want to be in charge of a software tool that I don't personally use. (I use xBA.)
* uBO-alike will have some amount of support burden, being a tool for regular users, some of whom know little or nothing about filter rules or how the tool operates. In other words, expect a subset of [this](https://github.com/gorhill/uBlock/issues?q=is%3Aissue+is%3Aclosed+label%3A%22filter+issue%22).

I don't think the second item would be that bad, necessarily, but to run uBO-alike you need to anticipate spending time helping newbies, the [ignorant](https://github.com/gorhill/uBlock/releases/tag/1.12.2), etc. Perhaps others would help you shoulder some of this support burden. But that would be entirely up to you, the owner of this project.

**Comment by Jon-guy30** [comment]
Hi, I just saw this. Thanks for publishing this, I'm going to use this instead of UBo. Even if you're not going to maintain this for long, I'm still going to stick to this version in Pale Moon. I read that UBo developer is not going to stop supporting the XUL version. But it's not the same as maintaining it. Why should you continue to use and update the xul version if more and more regressions start showing up and they're not gonna get fixed?

I use 1.14.22 in Seamonkey and I think I'm not gonna update it. I've updated it multiple times in sm, but it needs to be converted for it to work. 1.13.8 is the last working version for sm. 

UBo is the greatest "web blocker" program out there on the internet, it's too bad that the actions of Mozilla will eventually lead to Ublock Origin will start to suffer in the long term. It's (relatively) fine now, but what about future versions? 

Too bad I can't code, even if I did I don't think I would have motivation. I hope this project gains support, XUL browsers need a stable, working Ublock Origin! 

I'm not switching to chrome-like or chrome spy-browsers.

**Comment by joey04** [comment]
@Jon-guy30 thanks for your response. So I'm clear, by "going to use this" do you mean 1.14.16+bp1 or xulBlock Advanced (xBA)? 

<hr>

I wasn't intending to maintain 1.14.16+bp1. The hope is another developer will use that as the starting point for this proposed fork.

Now that I think about it, though, if anyone reading this is willing to use 1.14.16+bp1, either for testing purposes or for their real browsing, I'd be welcome to any feedback you have on it. It shares a lot in common with xBA, so using either helps both efforts.

**But let me be clear:** this is not full support for 1.14.16+bp1. So please don't ask me for help with how to use it or to un-break websites or anything. This is just a temporary "soliciting feedback support" until a heroic developer comes along to make a real project of it.

Really, I'm mostly interested about the backports (which is developer lingo for taking changes to newer versions of uBO then applying them back to this older version). I'm pretty confident it's fine, since I tested them thoroughly on 3 different browsers for xBA, but more testing is certainly welcome.

In particular, the backports are for asset management, removing all vestiges of the old way uBO used to do it long ago. So it's questions like, can it import and export settings properly? Can it select new lists, remove lists, update lists? How does it work with your own personal filters? Things like this are uBO assets management concerns.

**Comment by Jon-guy30** [comment]
I understand. 

I'm using xulBlockAdvanced, not 1.14.16+bp1. I could install it on seamonkey, but I use that browser for critical stuff, e.g. banking and government/state sites. I can't risk those sites breaking. Stock ubo+all filters (except HOSTs subscriptions) work fine on them, so 1.14.16+bp1 should work as well, but you never know.

**Comment by joey04** [comment]
Cool! I'm glad you're using xBA and liking it so far.

<hr>

Note: this is my edit on March 4th, a month after my initial response.

I didn't think to respond to all of Jon-guy30's last comment a month ago, but reading this again now, there's an important point to make here.

> Stock ubo+all filters (except HOSTs subscriptions) work fine on them, so 1.14.16+bp1 should work as well, but you never know.

If the concern is a matter of technical functionality, then I have little doubt that 1.14.16+bp1 will function as well as stock uBO 1.14.16.

As I mentioned earlier I only briefly tested it, but none of the changes were to the core filtering functionality. Only the list management behavior would potentially change, but as I said, I'm pretty confident it should be fine, because the same exact changes were made to xBA 1.0.
Thus far no problems have been reported, and if xBA list management is working fine in Pale Moon or another XUL browser, then it should work equally well in 1.14.16+bp1.

**Comment by joey04** [comment]
As explained in #13, I'm ending this project. So I'm closing this as well.

For those interested, I've already thoroughly documented xBA, including a number of issues, so please read all of that. It should explain many things.
