### ISSUE TITLE
works fine in SeaMonkey

### ISSUE THREAD

**Issue by joey04** [joey04/xulBlock-Advanced#3]
I've never used SeaMonkey and know little about it, so this is a request for SeaMonkey users who use uBlock Origin (uBO) in Advanced mode to try out xBA and provide feedback here.

I would like xulBlock Advanced (xBA) to support as many XUL browsers as feasible, but without having to personally test more than the three I've already vetted.

I'd like to know:
1. How well does xBA work on SeaMonkey?
2. What's the long-term viability of XUL support? I'm aware you're based on 52 ESR now, but what's beyond that?
3. What are proper settings for [install.rdf](https://github.com/joey04/xulBlock-Advanced/blob/master/src/install.rdf#L24)? (I left it unmodified from uBO's values.)

Note that xBA is only for Advanced user mode, so for the sake of this thread please only test xBA if you're already familiar with Advanced on uBO. Also, please read the documentation before installing, as xBA has important differences from uBO.

**Comment by Atavic** [comment]
- Seamonkey version 2.49.1

   User agent: Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0 SeaMonkey/2.49.1
   Build identifier: 20171016030418

- SeaMonkey has a slow development and I hope it will stay around for a while. Official info [here](http://forums.mozillazine.org/viewtopic.php?f=3&t=3029957), scroll down to *What we plan*.

- Install.rdf has `<em:maxVersion>*</em:maxVersion>` that's maybe too much, I'd put `2.*` but that's just me.

...it loads fine, got to test for a few days.

**Comment by joey04** [comment]
Thanks for the response and willingness to test it.

**Comment by joey04** [comment]
@Atavic - any updates?

**Comment by joey04** [comment]
Now that xBA is well-established, I'm changing my approach here to one of "assume-it's-fine-and-users-can-tell-me-otherwise".

The offer still stands for SeaMonkey users to test out xBA and report here. But given that no problems have been reported thus far, I'm closing this. It can be re-opened if needed.

And in terms of the big picture of SeaMonkey's future, we'll cross that bridge when it arrives.

**Comment by Atavic** [comment]
The SeaMonkey® Project is now at version 2.49.2
Being a conservative project, it most probably has broken anything related to xBA.
Going to check this weekend and post eventual issues.

**Comment by Atavic** [comment]
The SeaMonkey® Project is now at version 2.49.2
Being a conservative project, it most probably hasn't broken anything related to xBA.
Going to check this weekend and post eventual issues.

**Comment by joey04** [comment]
I appreciate you testing it out. But please don't feel obligated to do a thorough analysis. A brief test drive at several sites you're familiar with including some of your custom rules, plus a full list update should suffice.
